# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

name: CI
on:
  push:
    paths-ignore: ['*.md']
jobs:
  test:
    strategy:
      matrix:
        include:
          - { node: 14.x, vue: 2.5.x, platform: ubuntu-latest }
          - { node: 16.x, vue: 2.6.x, platform: windows-latest }
          - { node: 18.x, vue: 2.7.x, platform: macos-latest }
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install npm packages
        run: |
          npm ci
          npm install --no-save vue@"${{ matrix.vue }}" vue-template-compiler@"${{ matrix.vue }}"
      - run: npm test
